// Canonical registry of admin panel pages. Keep in sync with the frontend
// registry in technohana-frontend-master/src/lib/adminAccess.js.
export const ADMIN_PAGES = [
  "overview",
  "sales-dashboard",
  "sales-pipeline",
  "proposal-builder",
  "proposals",
  "enrollments",
  "enquiries",
  "testimonials",
  "quote-generator",
  "marketing-overview",
  "campaigns",
  "drip-sequences",
  "utm-report",
  "geo-analysis",
  "seo-analysis",
  "blogs",
  "courses",
  "subscribers",
  "referrals",
  "coupons",
  "instructors",
  "training-requirements",
  "team",
  "live-agent",
  "prompt-editor",
  "analytics",
  "ai-risk-reports",
  "crm",
  "seo-ops-dashboard",
  "seo-ops-opportunities",
  "seo-ops-competitors",
  "seo-ops-outreach",
  "seo-ops-published-links",
  "seo-ops-resource-pages",
  "seo-ops-reports",
  "seo-ops-monitoring",
  "seo-ops-analytics",
  "seo-ops-settings",
  "seo-intel-search-console",
  "seo-intel-analytics",
  "seo-intel-technical",
  "seo-intel-executive",
  "seo-intel-recommendations",
  "seo-intel-system-health",
  "seo-topic-clusters",
  "seo-internal-links",
  "authors",
];

export const ADMIN_ROLES = [
  "admin",
  "sales",
  "marketing",
  "super_admin",
  "trainer",
  "accounts",
  "hr",
  "student_support",
  "readonly",
  "analyst",
];

export const DEFAULT_PAGES_BY_ROLE = {
  admin: [...ADMIN_PAGES],
  super_admin: [...ADMIN_PAGES],
  sales: [
    "sales-dashboard",
    "sales-pipeline",
    "proposal-builder",
    "proposals",
    "enrollments",
    "enquiries",
    "testimonials",
    "quote-generator",
    "utm-report",
    "courses",
    "referrals",
    "analytics",
    "ai-risk-reports",
    "crm",
    "instructors",
    "training-requirements",
  ],
  marketing: [
    "marketing-overview",
    "campaigns",
    "drip-sequences",
    "utm-report",
    "geo-analysis",
    "seo-analysis",
    "analytics",
    "seo-ops-dashboard",
    "seo-ops-opportunities",
    "seo-ops-competitors",
    "seo-ops-outreach",
    "seo-ops-published-links",
    "seo-ops-resource-pages",
    "seo-ops-reports",
    "seo-ops-monitoring",
    "seo-ops-analytics",
    "seo-ops-settings",
    "seo-intel-search-console",
    "seo-intel-analytics",
    "seo-intel-technical",
    "seo-intel-executive",
    "seo-intel-recommendations",
    "seo-intel-system-health",
    "seo-topic-clusters",
    "seo-internal-links",
    "authors",
  ],
  // trainer/accounts/hr/student_support/readonly are CRM-only crmRoles — they
  // never get admin-panel pages (see authenticateAdmin.js CRM_ONLY_ROLES block),
  // so no entries here are needed for them.

  // Phase 6 — read-only admin-panel persona (Module 12). Gets view access to
  // every seo-ops-* page except Settings, and none of the seo-intel-* pages.
  // No requireMarketing/requireAdmin write route ever matches this role, so
  // every write endpoint 403s automatically without a dedicated middleware.
  analyst: [
    "seo-ops-dashboard",
    "seo-ops-opportunities",
    "seo-ops-competitors",
    "seo-ops-outreach",
    "seo-ops-published-links",
    "seo-ops-resource-pages",
    "seo-ops-reports",
    "seo-ops-monitoring",
    "seo-ops-analytics",
    "seo-topic-clusters",
    "seo-internal-links",
  ],
};

export const computeEffectivePages = (role, extraPages = [], revokedPages = []) => {
  const base = new Set([...(DEFAULT_PAGES_BY_ROLE[role] || []), ...extraPages]);
  for (const page of revokedPages) base.delete(page);
  return [...base].filter((page) => ADMIN_PAGES.includes(page));
};
