// Declarative registry of every collection reachable from Admin Global Search.
// Both search modes read from here: the keyword palette uses searchFields /
// identityFields / project / linkTo, and AI ask mode uses filterable / groupable.
//
// Two rules this file exists to enforce:
//   1. `project` is a WHITELIST. A secret added to a model later cannot leak
//      through a field this file never named. Never switch it to a blacklist.
//   2. No collection name is ever written as a string literal. Every entity
//      carries its Mongoose model, so a model rename fails at import instead of
//      silently returning nothing (the $unionWith chain in crm.controller.js
//      hardcodes "users"/"enquiries" and has exactly that failure mode).
//
// Machine/metric collections (SEO GSC+GA4 metrics, crawl pages, AI usage logs,
// course views, factory jobs) are deliberately absent: high volume, no text a
// human would ever search for.
import { User } from "../models/user.model.js";
import Enquiry from "../models/enquiry.model.js";
import { Order } from "../models/order.model.js";
import Proposal from "../models/proposal.model.js";
import Course from "../models/course.model.js";
import Batch from "../models/batch.model.js";
import Instructor from "../models/instructor.js";
import { Blogs } from "../models/blogs.model.js";
import Coupon from "../models/coupon.model.js";
import Testimonial from "../models/testimonial.model.js";
import Subscription from "../models/subscription.model.js";
import CareerApplication from "../models/careerApplication.model.js";
import InternApplication from "../models/internApplication.model.js";
import AdminUser from "../models/adminUser.model.js";
import CRMLead from "../models/crm/crmLead.model.js";
import CRMContact from "../models/crm/crmContact.model.js";
import CRMCompany from "../models/crm/crmCompany.model.js";
import CRMDeal from "../models/crm/crmDeal.model.js";

// Soft-delete guard shared by every CRM collection. Merged LAST in the query
// compiler so an AI-supplied filter can never unset it.
const NOT_DELETED = { isDeleted: { $ne: true } };

const DOT = " · ";

const join = (...parts) => parts.filter(Boolean).join(DOT);

const linkWithSearch = (path, term) =>
  term ? `${path}?search=${encodeURIComponent(term)}` : path;

export const SEARCH_ENTITIES = [
  {
    key: "enrollment",
    model: User,
    label: "Enrollments",
    icon: "Users",
    searchFields: ["name", "email", "phone", "company", "courseTitle", "city", "orderId", "couponCode", "certificateNumber"],
    identityFields: { email: ["email"], phone: ["phone"], ref: ["orderId", "certificateNumber", "couponCode"] },
    project: { name: 1, email: 1, phone: 1, company: 1, courseTitle: 1, status: 1, price: 1, currency: 1, city: 1, createdAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.courseTitle, d.status, d.company),
    linkTo: (d) => linkWithSearch("/admin/enrollments", d.email || d.name),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["pending-payment", "in-progress", "rejected", "enrolled", "completed"] },
      trainingType: { type: "enum", values: ["individual", "group", "corporate"] },
      userType: { type: "enum", values: ["professional", "student", "others"] },
      courseTitle: { type: "string" },
      company: { type: "string" },
      city: { type: "string" },
      currency: { type: "string" },
      couponCode: { type: "string" },
      participants: { type: "number" },
      progress: { type: "number" },
      createdAt: { type: "date" },
      enrolledAt: { type: "date" },
      completedAt: { type: "date" },
    },
    groupable: ["status", "courseTitle", "city", "trainingType", "currency", "userType"],
  },
  {
    key: "enquiry",
    model: Enquiry,
    label: "Enquiries",
    icon: "MessageSquare",
    searchFields: ["name", "email", "phone", "company", "courseTitle", "notes", "requirements", "domain", "assignedTo"],
    identityFields: { email: ["email"], phone: ["phone"], ref: [] },
    project: { name: 1, email: 1, phone: 1, company: 1, courseTitle: 1, status: 1, enquiryType: 1, price: 1, assignedTo: 1, createdAt: 1 },
    title: (d) => d.name || d.email || d.phone,
    subtitle: (d) => join(d.enquiryType, d.status, d.courseTitle),
    linkTo: (d) => linkWithSearch("/admin/enquiries", d.email || d.name),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["new", "contacted", "quoted", "won", "lost"] },
      trainingType: { type: "enum", values: ["individual", "group", "corporate"] },
      aiScoreBand: { type: "enum", values: ["hot", "warm", "cold"] },
      enquiryType: { type: "string" },
      courseTitle: { type: "string" },
      company: { type: "string" },
      source: { type: "string" },
      campaign: { type: "string" },
      assignedTo: { type: "string" },
      serviceLine: { type: "string" },
      lostReason: { type: "string" },
      aiScore: { type: "number" },
      createdAt: { type: "date" },
      nextFollowUp: { type: "date" },
    },
    groupable: ["status", "enquiryType", "source", "campaign", "assignedTo", "aiScoreBand", "courseTitle"],
  },
  {
    key: "crmLead",
    model: CRMLead,
    label: "CRM Leads",
    icon: "UserPlus",
    searchFields: ["name", "email", "phone", "whatsApp", "company", "designation", "city", "state", "country", "interest", "industry", "website"],
    identityFields: { email: ["email"], phone: ["phone", "whatsApp"], ref: [] },
    project: { name: 1, email: 1, phone: 1, company: 1, designation: 1, city: 1, country: 1, status: 1, priority: 1, leadScore: 1, createdAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.company, d.status, d.city),
    linkTo: (d) => linkWithSearch("/admin/crm", d.email || d.name),
    baseFilter: NOT_DELETED,
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["new", "discovery", "needs_analysis", "skill_gap_assessed", "course_recommended", "proposal_sent", "negotiation", "quotation_sent", "purchase_order", "won", "lost", "junk"] },
      priority: { type: "enum", values: ["low", "medium", "high", "urgent"] },
      source: { type: "enum", values: ["website", "referral", "event", "campaign", "cold_call", "social", "partner", "chat", "enquiry_form", "other"] },
      aiScoreBand: { type: "enum", values: ["hot", "warm", "cold"] },
      company: { type: "string" },
      country: { type: "string" },
      city: { type: "string" },
      industry: { type: "string" },
      currency: { type: "string" },
      leadScore: { type: "number" },
      expectedRevenue: { type: "number" },
      createdAt: { type: "date" },
      nextFollowUp: { type: "date" },
      wonAt: { type: "date" },
    },
    groupable: ["status", "priority", "source", "country", "city", "industry", "aiScoreBand"],
  },
  {
    key: "crmContact",
    model: CRMContact,
    label: "CRM Contacts",
    icon: "Contact",
    searchFields: ["firstName", "lastName", "email", "phone", "whatsApp", "designation", "department", "city", "country", "website"],
    identityFields: { email: ["email"], phone: ["phone", "whatsApp"], ref: [] },
    project: { firstName: 1, lastName: 1, email: 1, phone: 1, designation: 1, department: 1, city: 1, country: 1, createdAt: 1 },
    title: (d) => [d.firstName, d.lastName].filter(Boolean).join(" ") || d.email,
    subtitle: (d) => join(d.designation, d.city, d.country),
    linkTo: (d) => linkWithSearch("/admin/crm", d.email || d.firstName),
    baseFilter: NOT_DELETED,
    sort: { _id: -1 },
    filterable: {
      designation: { type: "string" },
      department: { type: "string" },
      city: { type: "string" },
      country: { type: "string" },
      isDecisionMaker: { type: "boolean" },
      isPrimaryContact: { type: "boolean" },
      createdAt: { type: "date" },
    },
    groupable: ["department", "country", "city", "designation"],
  },
  {
    key: "crmCompany",
    model: CRMCompany,
    label: "CRM Companies",
    icon: "Building2",
    searchFields: ["name", "email", "phone", "website", "industry", "subIndustry", "gst", "pan", "address.city", "address.country"],
    identityFields: { email: ["email"], phone: ["phone"], ref: ["gst", "pan"] },
    project: { name: 1, email: 1, phone: 1, website: 1, industry: 1, employeeRange: 1, "address.city": 1, "address.country": 1, createdAt: 1 },
    title: (d) => d.name,
    subtitle: (d) => join(d.industry, d.address && d.address.city, d.address && d.address.country),
    linkTo: (d) => linkWithSearch("/admin/crm", d.name),
    baseFilter: NOT_DELETED,
    sort: { _id: -1 },
    filterable: {
      industry: { type: "string" },
      subIndustry: { type: "string" },
      employeeRange: { type: "string" },
      "address.city": { type: "string" },
      "address.country": { type: "string" },
      annualRevenue: { type: "number" },
      employees: { type: "number" },
      createdAt: { type: "date" },
    },
    groupable: ["industry", "employeeRange", "address.country", "address.city"],
  },
  {
    key: "crmDeal",
    model: CRMDeal,
    label: "CRM Deals",
    icon: "Kanban",
    // assignedTo is an ObjectId ref to AdminUser here (unlike on Enquiry, where
    // it is a name string), so it is neither searchable nor filterable by text.
    searchFields: ["title", "quotationRef", "invoiceRef", "purchaseOrderRef", "stageKey"],
    identityFields: { email: [], phone: [], ref: ["quotationRef", "invoiceRef", "purchaseOrderRef"] },
    project: { title: 1, value: 1, currency: 1, status: 1, stageKey: 1, expectedCloseDate: 1, createdAt: 1 },
    title: (d) => d.title,
    subtitle: (d) => join(d.status, d.value != null ? [d.currency, d.value].filter(Boolean).join(" ") : null, d.stageKey),
    linkTo: () => "/crm",
    baseFilter: NOT_DELETED,
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["open", "won", "lost"] },
      stageKey: { type: "string" },
      currency: { type: "string" },
      value: { type: "number" },
      probability: { type: "number" },
      expectedCloseDate: { type: "date" },
      createdAt: { type: "date" },
      wonAt: { type: "date" },
    },
    groupable: ["status", "stageKey", "currency"],
  },
  {
    key: "order",
    model: Order,
    label: "Orders",
    icon: "Receipt",
    // razorpayPaymentId is searchable but never projected, so an admin pasting a
    // payment ID from the Razorpay dashboard can still find the order.
    searchFields: ["orderId", "invoiceNumber", "courseId", "couponCode", "referralCode", "razorpayPaymentId"],
    identityFields: { email: [], phone: [], ref: ["orderId", "invoiceNumber", "couponCode", "referralCode"] },
    project: { orderId: 1, invoiceNumber: 1, provider: 1, courseId: 1, currency: 1, status: 1, expectedTotalMinor: 1, couponCode: 1, totalDiscountPercent: 1, createdAt: 1 },
    title: (d) => d.invoiceNumber || d.orderId,
    subtitle: (d) => join(d.provider, d.status, d.courseId),
    linkTo: (d) => linkWithSearch("/admin/enrollments", d.orderId),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      provider: { type: "enum", values: ["stripe", "razorpay"] },
      status: { type: "string" },
      currency: { type: "string" },
      courseId: { type: "string" },
      couponCode: { type: "string" },
      enrollmentType: { type: "string" },
      expectedTotalMinor: { type: "number" },
      totalDiscountPercent: { type: "number" },
      participants: { type: "number" },
      createdAt: { type: "date" },
    },
    groupable: ["provider", "status", "currency", "courseId", "couponCode", "enrollmentType"],
  },
  {
    key: "proposal",
    model: Proposal,
    label: "Proposals",
    icon: "FileText",
    searchFields: ["refNum", "client.name", "client.company", "client.email", "client.phone", "notes"],
    identityFields: { email: ["client.email"], phone: ["client.phone"], ref: ["refNum"] },
    project: { refNum: 1, client: 1, type: 1, status: 1, validUntil: 1, totals: 1, createdBy: 1, createdAt: 1 },
    title: (d) => d.refNum,
    subtitle: (d) => join(d.client && (d.client.name || d.client.company), d.type, d.status),
    linkTo: (d) => linkWithSearch("/admin/proposals", d.refNum),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      type: { type: "enum", values: ["quote", "proposal"] },
      status: { type: "enum", values: ["draft", "sent", "accepted", "expired"] },
      "client.company": { type: "string" },
      createdBy: { type: "string" },
      "totals.currency": { type: "string" },
      "totals.grandTotalMinor": { type: "number" },
      validUntil: { type: "date" },
      createdAt: { type: "date" },
    },
    groupable: ["type", "status", "createdBy", "totals.currency"],
  },
  {
    key: "course",
    model: Course,
    label: "Courses",
    icon: "GraduationCap",
    searchFields: ["courseTitle", "category", "categoryGroup", "instructor", "courseSlug", "id"],
    identityFields: { email: [], phone: [], ref: ["id", "courseSlug"] },
    project: { courseTitle: 1, courseSlug: 1, id: 1, category: 1, categoryGroup: 1, instructor: 1, difficulty: 1, language: 1, rating: 1, prices: 1, createdAt: 1 },
    title: (d) => d.courseTitle,
    subtitle: (d) => join(d.category, d.difficulty, d.instructor),
    linkTo: (d) => linkWithSearch("/admin/courses", d.courseTitle),
    baseFilter: {},
    sort: { courseTitle: 1 },
    filterable: {
      category: { type: "string" },
      categoryGroup: { type: "string" },
      instructor: { type: "string" },
      difficulty: { type: "string" },
      language: { type: "string" },
      // rating and noStudents are Strings in the course schema, so they are
      // declared as strings here: a gt/gte on them would compare
      // lexicographically and quietly return the wrong courses. The compiler
      // rejects range operators on a string field instead.
      rating: { type: "string" },
      noStudents: { type: "string" },
      createdAt: { type: "date" },
    },
    groupable: ["category", "categoryGroup", "instructor", "difficulty", "language"],
  },
  {
    key: "batch",
    model: Batch,
    label: "Batches",
    icon: "CalendarDays",
    searchFields: ["batchCode", "name", "courseTitle", "instructorName", "location", "notes"],
    identityFields: { email: [], phone: [], ref: ["batchCode"] },
    project: { batchCode: 1, name: 1, courseTitle: 1, instructorName: 1, location: 1, deliveryMode: 1, status: 1, startDate: 1, endDate: 1, capacity: 1, enrolledCount: 1, createdAt: 1 },
    title: (d) => d.batchCode || d.name,
    subtitle: (d) => join(d.courseTitle, d.status, d.instructorName),
    linkTo: (d) => linkWithSearch("/admin/batches", d.batchCode || d.courseTitle),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["draft", "scheduled", "in-progress", "completed", "cancelled"] },
      deliveryMode: { type: "enum", values: ["online", "onsite", "hybrid"] },
      trainingType: { type: "enum", values: ["individual", "group", "corporate"] },
      batchType: { type: "enum", values: ["weekday-morning", "weekday-evening", "weekend", "custom"] },
      courseTitle: { type: "string" },
      instructorName: { type: "string" },
      location: { type: "string" },
      capacity: { type: "number" },
      enrolledCount: { type: "number" },
      startDate: { type: "date" },
      endDate: { type: "date" },
      createdAt: { type: "date" },
    },
    groupable: ["status", "deliveryMode", "trainingType", "courseTitle", "instructorName", "location"],
  },
  {
    key: "instructor",
    model: Instructor,
    label: "Instructors",
    icon: "UserCheck",
    searchFields: ["name", "email", "phone", "expertise", "expertiseOther", "linkedinUrl", "notes", "assignedTo"],
    identityFields: { email: ["email"], phone: ["phone"], ref: [] },
    project: { name: 1, email: 1, phone: 1, expertise: 1, experience: 1, deliveryMode: 1, status: 1, dailyRate: 1, isActive: 1, submittedAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.expertise, d.status, d.experience),
    linkTo: (d) => linkWithSearch("/admin/instructors", d.email || d.name),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "string" },
      expertise: { type: "string" },
      deliveryMode: { type: "string" },
      assignedTo: { type: "string" },
      isActive: { type: "boolean" },
      submittedAt: { type: "date" },
      nextFollowUp: { type: "date" },
    },
    groupable: ["status", "expertise", "deliveryMode", "assignedTo"],
  },
  {
    key: "blog",
    model: Blogs,
    label: "Blogs",
    icon: "BookOpen",
    searchFields: ["title", "slug", "author", "category", "excerpt", "focusKeyword", "metaTitle"],
    identityFields: { email: [], phone: [], ref: ["slug"] },
    project: { title: 1, slug: 1, author: 1, category: 1, excerpt: 1, focusKeyword: 1, published: 1, contentType: 1, date: 1, readTimeMin: 1, createdAt: 1 },
    title: (d) => d.title,
    subtitle: (d) => join(d.category, d.published ? "published" : "draft", d.author),
    linkTo: (d) => linkWithSearch("/admin/blogs", d.title),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      category: { type: "string" },
      author: { type: "string" },
      focusKeyword: { type: "string" },
      contentType: { type: "string" },
      published: { type: "boolean" },
      readTimeMin: { type: "number" },
      createdAt: { type: "date" },
      scheduledAt: { type: "date" },
    },
    groupable: ["category", "author", "contentType", "published"],
  },
  {
    key: "coupon",
    model: Coupon,
    label: "Coupons",
    icon: "Ticket",
    searchFields: ["code", "description", "notes"],
    identityFields: { email: [], phone: [], ref: ["code"] },
    project: { code: 1, discountPercent: 1, description: 1, validCurrencies: 1, isActive: 1, expiryDate: 1, startDate: 1, maxUsageCount: 1, currentUsageCount: 1, createdAt: 1 },
    title: (d) => d.code,
    subtitle: (d) => join(`${d.discountPercent}% off`, d.isActive ? "active" : "inactive"),
    linkTo: (d) => linkWithSearch("/admin/coupons", d.code),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      isActive: { type: "boolean" },
      discountPercent: { type: "number" },
      currentUsageCount: { type: "number" },
      maxUsageCount: { type: "number" },
      expiryDate: { type: "date" },
      startDate: { type: "date" },
      createdAt: { type: "date" },
    },
    groupable: ["isActive", "discountPercent"],
  },
  {
    key: "testimonial",
    model: Testimonial,
    label: "Testimonials",
    icon: "Star",
    searchFields: ["name", "email", "courseTitle", "review"],
    identityFields: { email: ["email"], phone: [], ref: [] },
    project: { name: 1, email: 1, courseTitle: 1, rating: 1, review: 1, status: 1, canPublish: 1, createdAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.courseTitle, d.status, d.rating ? `${d.rating}★` : null),
    linkTo: (d) => linkWithSearch("/admin/testimonials", d.email || d.name),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["pending", "approved", "rejected"] },
      courseTitle: { type: "string" },
      rating: { type: "number" },
      canPublish: { type: "boolean" },
      createdAt: { type: "date" },
    },
    groupable: ["status", "courseTitle", "rating"],
  },
  {
    key: "subscriber",
    model: Subscription,
    label: "Subscribers",
    icon: "Mail",
    searchFields: ["email", "subscribeTo"],
    identityFields: { email: ["email"], phone: [], ref: [] },
    project: { email: 1, subscribeTo: 1, isActive: 1, createdAt: 1 },
    title: (d) => d.email,
    subtitle: (d) => join(d.subscribeTo, d.isActive ? "active" : "unsubscribed"),
    linkTo: (d) => linkWithSearch("/admin/subscribers", d.email),
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      subscribeTo: { type: "string" },
      isActive: { type: "boolean" },
      createdAt: { type: "date" },
    },
    groupable: ["subscribeTo", "isActive"],
  },
  {
    key: "careerApplication",
    model: CareerApplication,
    label: "Career Applications",
    icon: "Briefcase",
    searchFields: ["name", "email", "phone", "expertise", "coverLetter", "adminNotes"],
    identityFields: { email: ["email"], phone: ["phone"], ref: [] },
    project: { name: 1, email: 1, phone: 1, expertise: 1, status: 1, submittedAt: 1, createdAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.expertise, d.status),
    // No admin page for career applications yet, so these render as
    // non-clickable informational rows rather than being dropped from search.
    linkTo: () => null,
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["applied", "shortlisted", "accepted", "rejected"] },
      expertise: { type: "string" },
      submittedAt: { type: "date" },
      createdAt: { type: "date" },
    },
    groupable: ["status", "expertise"],
  },
  {
    key: "internApplication",
    model: InternApplication,
    label: "Intern Applications",
    icon: "GraduationCap",
    searchFields: ["name", "email", "phone", "college", "degree", "linkedinUrl", "coverLetter", "notes", "assignedTo"],
    identityFields: { email: ["email"], phone: ["phone"], ref: [] },
    project: { name: 1, email: 1, phone: 1, college: 1, degree: 1, department: 1, graduationYear: 1, status: 1, assignedTo: 1, submittedAt: 1, createdAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.department, d.status, d.college),
    linkTo: () => null,
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      status: { type: "enum", values: ["applied", "shortlisted", "interviewing", "offered", "hired", "rejected"] },
      department: { type: "enum", values: ["sales", "marketing", "engineering", "design"] },
      college: { type: "string" },
      degree: { type: "string" },
      assignedTo: { type: "string" },
      source: { type: "string" },
      // String in the schema, so declared string here — see the note on
      // course.rating about lexicographic range comparisons.
      graduationYear: { type: "string" },
      submittedAt: { type: "date" },
      createdAt: { type: "date" },
    },
    groupable: ["status", "department", "college", "source"],
  },
  {
    key: "adminUser",
    model: AdminUser,
    label: "Team",
    icon: "Shield",
    searchFields: ["name", "email", "role", "crmRole"],
    identityFields: { email: ["email"], phone: [], ref: [] },
    project: { name: 1, email: 1, role: 1, crmRole: 1, active: 1, lastLoginAt: 1, createdAt: 1 },
    title: (d) => d.name || d.email,
    subtitle: (d) => join(d.role, d.active ? "active" : "disabled"),
    linkTo: () => "/admin/team",
    baseFilter: {},
    sort: { _id: -1 },
    filterable: {
      role: { type: "enum", values: ["admin", "sales", "analyst", "marketing"] },
      crmRole: { type: "string" },
      active: { type: "boolean" },
      lastLoginAt: { type: "date" },
      createdAt: { type: "date" },
    },
    groupable: ["role", "crmRole", "active"],
  },
];

export const ENTITY_KEYS = SEARCH_ENTITIES.map((e) => e.key);

export const getEntity = (key) => SEARCH_ENTITIES.find((e) => e.key === key) || null;
